theme: jekyll-theme-cayman
title: Joshua McNew's ePortfolio
description: CS499 Computer Science Capstone

# SITE CONFIGURATION
baseurl: ""
url: "https://iMcNeW.github.io"
markdown: kramdown
kramdown: true
parse_block_html: true
